### ISSUE TITLE
Modalità scura/chiara non viene mantenuta su tutto il sito una volta cambiata

### ISSUE THREAD

**Issue by Tammura** [PoliNetworkOrg/polinetwork.github.io#277]
Al caricamento della home il sito viene visualizzato con la modalità (scura/chiara) del dispositivo, ma se scegliessi una diversa da quella del mio dispositivo e andassi su un'altro link del sito la pagina nuova viene di nuovo ricaricata con la modalità del mio dispositivo e non tiene quella che ho cambiato io.

https://user-images.githubusercontent.com/72708024/209449156-31a1fc6f-72b2-4207-9e12-39bf44e5803b.mov

Il problema l'ho riscontrato sia su Safari che su Chrome

**Comment by Eliaxie** [comment]
"it's a feature not a bug"
We do this so we don't have to use localStorage and therefore we don't need to have a privacy policy for the website.
